summary(mtcars)
mean (mtcars$mpg)
sd(mtcars$mpg)
max(mtcars$mpg)
min(mtcars$mpg)
boxplot(mtcars$mpg)
mtcars$mpg
length(mtcars$mpg)
plot(mtcars$mpg, mtcars$cyl)
barplot(mtcars$mpg)
print ("hello guys")
